### ISSUE TITLE
Babble-Spell.Lua-Error

### ISSUE THREAD

**Issue by Mixuspidelix** [Aviana/LunaUnitFrames#335]
http://www.bilder-upload.eu/show.php?file=85127e-1511024038.jpg

**Comment by Aviana** [comment]
should be fixed in master

**Comment by Mixuspidelix** [comment]
download the newest master-version and put the old wtf.lua files out but the Lua-Error is still there... :(
