### ISSUE TITLE
do not show debuffs at mid square and always hightlighting

### ISSUE THREAD

**Issue by Melazul** [Aviana/LunaUnitFrames#817]
subj. do not show in middle square dispellable debuffs, also raid frames always got debuff type hightligting even if it off. On default profile same issue.
![WoWScrnShot_020921_143720](https://user-images.githubusercontent.com/78789492/107359786-2a526f80-6ae6-11eb-8845-25506424aac3.jpg)
![WoWScrnShot_020921_144635](https://user-images.githubusercontent.com/78789492/107359794-2c1c3300-6ae6-11eb-9335-226b0c642e17.jpg)
![WoWScrnShot_020921_144613](https://user-images.githubusercontent.com/78789492/107359796-2c1c3300-6ae6-11eb-9219-bc1fabf927a5.jpg)
![WoWScrnShot_020921_144609](https://user-images.githubusercontent.com/78789492/107359800-2cb4c980-6ae6-11eb-93e4-ceb2d7065313.jpg)

**Comment by Aviana** [comment]
Fixed both in 4060.

**Comment by Melazul** [comment]
actually still doesnt show anything in middle square

  
>Среда, 24 февраля 2021, 20:33 +03:00 от Aviana <notifications@github.com>:
> 
> 
>Fixed both in 4060.
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe . 
 
 
--

**Comment by Aviana** [comment]
Dispels now fixed in all squares.
